Controllers/DeveloperGuideController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Mvc.Boilerplate.Controllers
{
    public class DeveloperGuideController : Controller
    {
        public ActionResult BuiltOn()
        {
            return View();
        }

        public ActionResult Conventions()
        {
            return View();
        }

        public ActionResult StyleGuide()
        {
            return View("Index");
        }

        
        //
        // GET: /StyleGuide/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Menus()
        {

            return ShowGuideSection("Menu");
        }

        public ActionResult Tabs()
        {
            return ShowGuideSection("Tabs");
        }

        public ActionResult Grids()
        {
            return ShowGuideSection("Grids");
        }

        public ActionResult Tables()
        {
            return ShowGuideSection("Tables");
        }

        public ActionResult Accordions()
        {
            return ShowGuideSection("Accordions");
        }

        public ActionResult InputWidgets()
        {
            return ShowGuideSection("InputWidgets");
        }

        public ActionResult ShowGuideSection(string sectionName)
        {
            switch (sectionName)
            {
                case "ColourSchema" :
                    ViewBag.SectionAnchorName = "dev-guide-colourschema";
                    ViewBag.SectionName = "_ColourSchema";
                    ViewBag.SectionFriendlyName = "Colour Schema";
                    break;
                case "Forms":
                    ViewBag.SectionAnchorName = "dev-guide-forms";
                    ViewBag.SectionName = "_Forms";
                    ViewBag.SectionFriendlyName = "Forms";
                    break;
                case "Grids":
                    ViewBag.SectionAnchorName = "dev-guide-grids";
                    ViewBag.SectionName = "_Grids";
                    ViewBag.SectionFriendlyName = "Grids";
                    break;
                case "Tables":
                    ViewBag.SectionAnchorName = "dev-guide-tables";
                    ViewBag.SectionName = "_Tables";
                    ViewBag.SectionFriendlyName = "Tables";
                    break;
                case "InlineStyles":
                    ViewBag.SectionAnchorName = "dev-guide-inlinestyles";
                    ViewBag.SectionName = "_InlineStyles";
                    ViewBag.SectionFriendlyName = "Inline Styles";
                    break;
                case "Menu":
                    ViewBag.SectionName = "_Menu";
                    ViewBag.SectionAnchorName = "dev-guide-menu";
                    ViewBag.SectionFriendlyName = "Menu";
                    break;
                case "Tabs":
                    ViewBag.SectionAnchorName = "dev-guide-tabs";
                    ViewBag.SectionName = "_Tabs";
                    ViewBag.SectionFriendlyName = "Tabs";
                    break;
                case "Accordions" :
                    ViewBag.SectionAnchorName = "dev-guide-accordions";
                    ViewBag.SectionName = "_Accordions";
                    ViewBag.SectionFriendlyName = "Accordions";
                    break;
                case "InputWidgets":
                    ViewBag.SectionAnchorName = "dev-guide-inputwidgets";
                    ViewBag.SectionName = "_InputWidgets";
                    ViewBag.SectionFriendlyName = "Input Widgets";
                    break;
                default :
                    ViewBag.SectionName = "_Blank";
                    break;
            }

            return View("GuideSection");
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Mvc.Boilerplate.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/

        public ActionResult Index()
        {
            return View();
        }

    }
}

Controllers/TestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Mvc.Boilerplate.Controllers
{
    public class TestController : Controller
    {
        //
        // GET: /Test/

        public ActionResult Index()
        {
            return View();
        }

    }
}

Views/DeveloperGuide/BuiltOn.cshtml
@{
    ViewBag.Title = "MVC Boilerplate";
    ViewBag.SubTitle = "is ready assembled plumbing and UX compatibility provisioning, standing on the shoulders of these giants...";    

    ViewBag.CurrentNav = "BuiltOn";
    ViewBag.UseGoogleAnalytics = false;                
}


<div class="building-block">
    <img src="@Url.Content("~/Content/img/boilerplate-devguide/bootstrap_logo.png")" alt="bootstrap twitter logo" width="200px" />
    <div class="colophon">
        <h3>Bootstrap</h3>
        <p>
            MVC Boilerplate uses Twitter Bootstrap as its core css reset and widget library.
        </p>
    </div>
</div>

<div class="building-block">
    <img src="@Url.Content("~/Content/img/boilerplate-devguide/less_logo.png")" alt="less css logo"  width="200px" />
    <div class="colophon">
        <h3>Less CSS</h3>
        <p>
            Bootstrap and Boilerplate both use Less CSS to keep the CSS maintainable and flexible.

            The Boilerplate Visual Studio Build process invokes DotLess to compile these working versions of Less into production ready CSS.
        </p>
    </div>
</div>

<div class="building-block">
    <img src="@Url.Content("~/Content/img/boilerplate-devguide/jquery_logo.png")" alt="jquery logo"  width="200px" />
    <div class="colophon">
    <h3>jQuery</h3>
    <p>
        Of course.
    </p>
    </div>
</div>

<div class="building-block">
    <img src="@Url.Content("~/Content/img/boilerplate-devguide/jquery-ui_logo.png")" alt="jquery ui logo"  width="200px" />
    <div class="colophon">
        <h3>jQuery UI</h3>
        <p>
            Boilerplate compatible themes are included for jQuery UI, samples are included in the Developer Guide and it is referenced by default in the application.
        </p>
    </div>
</div>

<div class="building-block">
    <img src="@Url.Content("~/Content/img/boilerplate-devguide/kendo-ui_logo.png")" alt="jquery ui logo"  width="200px" />
    <div class="colophon">
        <h3>Kendo UI</h3>
        <p>
            Boilerplate compatible themes are included for Kendo UI Web (by Telerik), samples are included in the Developer Guide and it is referenced by default in the application.
        </p>
    </div>
</div>

<div class="building-block">
    <img src="@Url.Content("~/Content/img/boilerplate-devguide/telerik_logo.png")" alt="jquery ui logo"  width="200px" />
    <div class="colophon">
        <h3>Telerik MVC UI Extensions</h3>
        <p>
            Boilerplate compatible themes are included for Telerik MVC UI Extensions, but since this is a commerical product if you wish you use it you should reference it seperately.
        </p>
    </div>
</div>

Views/DeveloperGuide/GuideSection.cshtml
@{
    ViewBag.Title = "GuideSection";

    ViewBag.CurrentNav = "Style";
    ViewBag.UseGoogleAnalytics = false;        
}

<h2>GuideSection</h2>

<ul class="mui-breadcrumbs">
    <li><a href="Index">Style Guide</a></li>
    <li class="ui-state-active"><a href="#">@ViewBag.SectionFriendlyName</a></li>
</ul>


@Html.Partial((string)ViewBag.SectionName)

<script type="text/javascript" language="javascript">
    $(document).ready(function () {
        prettyPrint();
    });
</script>

Views/DeveloperGuide/Index.cshtml
@{
    ViewBag.Title = "Style Guide";
    ViewBag.SubTitle = "MVC Boilerplate is Bootstrap + Third Party Widget library CSS converted to .less for themeability. Giving you a common ground.";    

    ViewBag.CurrentNav = "Style";
    ViewBag.UseGoogleAnalytics = false;            
}

@section SideNavigation {
    @Html.Partial("Layout/_SideNavigation")
}

The following Style Guide is taken mainly from Twitter's Bootstrap, but rehashed including other popular widget libraries and extensions to give you a common look up point for styles and assets.

@Html.Partial("_Typography")

@Html.Partial("_Code")

@Html.Partial("_Tables")

@Html.Partial("_Grids")

@Html.Partial("_Forms")

@Html.Partial("_Dropdowns")

@Html.Partial("_Buttons")

@Html.Partial("_ButtonGroups")

@Html.Partial("_Navs")

@Html.Partial("_NavBar")

@Html.Partial("_BreadCrumbsPagination")

@Html.Partial("_LabelsAndBadges")

@Html.Partial("_Images")

@Html.Partial("_Icons")

@Html.Partial("_ColourSchema")

@Html.Partial("_InlineStyles")




@Html.Partial("_Accordions")

@Html.Partial("_InputWidgets")

<script type="text/javascript" language="javascript">
    $(document).ready(function () {
        prettyPrint();
    });
</script>

Views/DeveloperGuide/Layout/_GoogleAnalytics.cshtml
        <!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
        <script>
            var _gaq = [['_setAccount', 'UA-XXXXX-X'], ['_trackPageview']];
            (function (d, t) {
                var g = d.createElement(t), s = d.getElementsByTagName(t)[0];
                g.src = ('https:' == location.protocol ? '//ssl' : '//www') + '.google-analytics.com/ga.js';
                s.parentNode.insertBefore(g, s)
            } (document, 'script'));
        </script>

Views/DeveloperGuide/Layout/_Header.cshtml
        <header class="jumbotron subhead">
            <div class="container">
                <h1>@ViewBag.Title</h1>
                <div class="tag-line">@ViewBag.SubTitle</div>
            </div>
        </header>

Views/DeveloperGuide/Layout/_Layout.cshtml
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>@ViewBag.Title</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
        <link rel="stylesheet" type="text/css"  href="@Url.Content("~/Content/css/kendo.common.min.css")">
        <link rel="stylesheet" type="text/css"  href="@Url.Content("~/Content/css/kendo.default.min.css")">
        <link rel="stylesheet" type="text/css"  href="@Url.Content("~/Content/css/slick.grid.css")">
        
        <link rel="stylesheet" type="text/css"  href="@Url.Content("~/Content/css/jquery.multiselect.css")">
        <link rel="stylesheet" type="text/css"  href="@Url.Content("~/Content/css/jquery.multiselect.filter.css")">

        <link rel="stylesheet/less" type="text/css" href="@Url.Content("~/Content/css/mvc.boilerplate/mvc.boilerplate.less")">

        <script src="@Url.Content("~/Content/scripts/lib/modernizr-2.6.1.min.js")"></script>
        
        <script src="@Url.Content("~/Content/scripts/lib/less-1.3.0.min.js")"></script>

        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.0/jquery.min.js"></script>
        <script> window.jQuery || document.write('<script src="@Url.Content("~/Content/scripts/lib/jquery-1.8.0.min.js")"><\/script>')</script>
        <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.9.1/jquery-ui.min.js"></script>
        <script> (jQuery.ui) || document.write('<script src="@Url.Content("~/Content/scripts/lib/jquery-ui-1.9.1.min.js")"><\/script>')</script>

        <script src="@Url.Content("~/Content/scripts/lib/kendo.web.min.js")"></script>
        <script src="@Url.Content("~/Content/scripts/lib/prettify.js")"></script>
        <script src="@Url.Content("~/Content/scripts/lib/jquery.event.drag-2.0.min.js")"></script>
        <script src="@Url.Content("~/Content/scripts/lib/slick.core.js")"></script>
        <script src="@Url.Content("~/Content/scripts/lib/slick.grid.js")"></script>

        <script src="@Url.Content("~/Content/scripts/lib/jquery.multiselect.js")"></script>
        <script src="@Url.Content("~/Content/scripts/lib/jquery.multiselect.filter.js")"></script>

        <script src="@Url.Content("~/Content/scripts/lib/jquery.splitbutton.js")"></script>

        <script src="@Url.Content("~/Content/scripts/lib/html.encode.decode.js")"></script>
        <script src="@Url.Content("~/Content/scripts/lib/mvc-boilerplate.utility.js")"></script>
        
        
        <script src="@Url.Content("~/Content/scripts/bootstrap/bootstrap-transition.js")"></script>
        <script src="@Url.Content("~/Content/scripts/bootstrap/bootstrap-alert.js")"></script> 
        <script src="@Url.Content("~/Content/scripts/bootstrap/bootstrap-modal.js")"></script>
        <script src="@Url.Content("~/Content/scripts/bootstrap/bootstrap-dropdown.js")"></script>
        <script src="@Url.Content("~/Content/scripts/bootstrap/bootstrap-scrollspy.js")"></script>
        <script src="@Url.Content("~/Content/scripts/bootstrap/bootstrap-tab.js")"></script>
        <script src="@Url.Content("~/Content/scripts/bootstrap/bootstrap-tooltip.js")"></script>
        <script src="@Url.Content("~/Content/scripts/bootstrap/bootstrap-popover.js")"></script>
        <script src="@Url.Content("~/Content/scripts/bootstrap/bootstrap-button.js")"></script> 
        <script src="@Url.Content("~/Content/scripts/bootstrap/bootstrap-collapse.js")"></script>
        <script src="@Url.Content("~/Content/scripts/bootstrap/bootstrap-carousel.js")"></script>
        <script src="@Url.Content("~/Content/scripts/bootstrap/bootstrap-typeahead.js")"></script>
        <script src="@Url.Content("~/Content/scripts/bootstrap/bootstrap-affix.js")"></script> 

        <script src="@Url.Content("~/Content/scripts/boilerplate/slickgrid-initialiser.js")"></script>
        
        <script src="@Url.Content("~/Content/scripts/boilerplate-devguide/application.js")"></script>

        
        
    </head>
    <body class="style-guide" data-spy="scroll" data-target=".side-navigation" data-twttr-rendered="true">
        <!--[if lt IE 7]>
            <p class="chromeframe">You are using an outdated browser. <a href="http://browsehappy.com/">Upgrade your browser today</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to better experience this site.</p>
        <![endif]-->

        @Html.Partial("Layout/_Navbar")
        @Html.Partial("Layout/_Header")

        <!-- Add your site or application content here -->
        <div class="container">
            <div class="row">
                <div class="@Html.AttributeEncode((IsSectionDefined("SideNavigation")) ? "span3 side-navigation" : "ui-helper-hidden")">
                    @RenderSection("SideNavigation", false)
                </div>

                <div class="@Html.AttributeEncode((IsSectionDefined("SideNavigation")) ? "span9 " : "span12 ")content-panel">
                    @RenderBody()
                </div>
            </div>
        </div>

        @if (ViewBag.UseGoogleAnalytics)
        {
            @Html.Partial("Layout/_GoogleAnalytics")
        }
    </body>
</html>

Views/DeveloperGuide/Layout/_Navbar.cshtml
        <div class="navbar navbar-fixed-top">
          <div class="navbar-inner">
            <a class="brand" href="#">MVC Boilerplate</a>
            <ul class="nav">
                
              <li class="@Html.AttributeEncode((ViewBag.CurrentNav == "BuiltOn") ? "active" : "")"><a href="@Url.Action("BuiltOn")">Built On</a></li>
              <li class="@Html.AttributeEncode((ViewBag.CurrentNav == "Conventions") ? "active" : "")"><a href="@Url.Action("Conventions")">Conventions</a></li>
              <li class="@Html.AttributeEncode((ViewBag.CurrentNav == "Style") ? "active" : "")"><a href="@Url.Action("StyleGuide")">And Style</a></li>
            </ul>
          </div>
        </div>

Views/DeveloperGuide/Layout/_SideNavigation.cshtml
<ul class="nav nav-list side-navigation-list">
    <li class=""><a href="#dev-guide-typography"><i class="icon-chevron-right"></i>Typography</a></li>
    <li class=""><a href="#dev-guide-code"><i class="icon-chevron-right"></i>Code</a></li>
    <li class=""><a href="#dev-guide-tables"><i class="icon-chevron-right"></i>Tables</a></li>
    <li class=""><a href="#dev-guide-grids"><i class="icon-chevron-right"></i>Grids</a></li>
    <li class=""><a href="#dev-guide-forms"><i class="icon-chevron-right"></i>Forms</a></li>
    <li class=""><a href="#dev-guide-dropdowns"><i class="icon-chevron-right"></i>Dropdowns</a></li>
    <li class=""><a href="#dev-guide-buttons"><i class="icon-chevron-right"></i>Buttons</a></li>
    <li class=""><a href="#dev-guide-buttongroups"><i class="icon-chevron-right"></i>Button Groups</a></li>
    <li class=""><a href="#dev-guide-navs"><i class="icon-chevron-right"></i>Navs, Tabs, Pills</a></li>
    <li class=""><a href="#dev-guide-navbar"><i class="icon-chevron-right"></i>Navbar</a></li>
    <li class=""><a href="#dev-guide-breadcrumbs"><i class="icon-chevron-right"></i>Bread Crumbs / Pagination</a></li>


    <li class=""><a href="#dev-guide-images"><i class="icon-chevron-right"></i>Images</a></li>
    <li class=""><a href="#dev-guide-icons"><i class="icon-chevron-right"></i>Icons</a></li>
    
    <li class=""><a href="#dev-guide-colourschema"><i class="icon-chevron-right"></i>Colour Schema</a></li>
    
    
    <li class=""><a href="#dev-guide-inlinestyles"><i class="icon-chevron-right"></i>Inline Styles</a></li>
    <li class=""><a href="#dev-guide-accordions"><i class="icon-chevron-right"></i>Accordions</a></li>
    <li class=""><a href="#dev-guide-inputwidgets"><i class="icon-chevron-right"></i>Input Widgets</a></li>
</ul>

Views/DeveloperGuide/_Code.cshtml
<!-- Code
================================================== -->
<section id="dev-guide-code">
    <div class="page-header">
    <h1>Code</h1>
    </div>

    <h2>Inline</h2>
    <p>Wrap inline snippets of code with <code>&lt;code&gt;</code>.</p>
    <div class="bs-docs-example">
    For example, <code>&lt;section&gt;</code> should be wrapped as inline.
    </div>
<pre class="prettyprint">
For example, &lt;code&gt;&lt;section&gt;&lt;/code&gt; should be wrapped as inline.
</pre>

    <h2>Basic block</h2>
    <p>Use <code>&lt;pre&gt;</code> for multiple lines of code. Be sure to escape any angle brackets in the code for proper rendering.</p>
    <div class="bs-docs-example">
    <pre>&lt;p&gt;Sample text here...&lt;/p&gt;</pre>
    </div>

<pre class="prettyprint" style="margin-bottom: 9px;">
&lt;pre&gt;
&amp;lt;p&amp;gt;Sample text here...&amp;lt;/p&amp;gt;
&lt;/pre&gt;
</pre>

    <p><span class="label label-info">Heads up!</span> Be sure to keep code within <code>&lt;pre&gt;</code> tags as close to the left as possible; it will render all tabs.</p>
    <p>You may optionally add the <code>.pre-scrollable</code> class which will set a max-height of 350px and provide a y-axis scrollbar.</p>
</section>

Views/DeveloperGuide/_ColourSchema.cshtml
<section id="dev-guide-colourschema">
<h2>Colour Schema</h2>
@ViewBag.SectionAnchorName
<ul class="style-guide-colour-list ui-helper-clearfix">
    <li class="style-guide-base-color">@@base-color</li>
    <li class="style-guide-selection-color">@@selection-color</li>
    <li class="style-guide-base-content-color">@@base-content-color</li>
    <li class="style-guide-base-content-border-color">@@base-content-border-color</li>
    <li class="style-guide-widget-header-border-color">@@widget-header-border-color</li>
    <li class="style-guide-widget-header-background-color">@@widget-header-background-color</li>
    <li class="style-guide-widget-header-border-color">@@widget-header-border-color</li>
    <li class="style-guide-widget-header-background-color">@@widget-header-background-color</li>
    <li class="style-guide-widget-default-color">@@widget-default-color</li>
    <li class="style-guide-widget-default-border-color">@@widget-default-border-color</li>
    <li class="style-guide-widget-default-background-color">@@widget-default-background-color</li>
    <li class="style-guide-widget-hover-color">@@widget-hover-color</li>
    <li class="style-guide-widget-hover-border-color">@@widget-hover-border-color</li>
    <li class="style-guide-widget-hover-background-color">@@widget-hover-background-color</li>
    <li class="style-guide-widget-active-color">@@widget-active-color</li>
    <li class="style-guide-widget-active-border-color">@@widget-active-border-color</li>
    <li class="style-guide-widget-active-background-color">@@widget-active-background-color</li>
</ul>


<script language="javascript" type="text/javascript">
    $(document).ready(function () {
        $("ul.style-guide-colour-list>li").each(function () {
            var $this = $(this);
            var classList = $this.attr('class').split(/\s+/);
            $(classList).each(function (index) {
                var className = String(this);
                if (className.substr(0, 11) == "style-guide") {
                    var guideText = $this.text();
                    $this
                        .text("")
                        .removeClass(className)
                        .prepend("<div class='" + className + " style-guide-colour-swatch'></div>")
                        .append("<ul><li class='style-guide-colour-name'>" + guideText + "</li><li class='style-guide-colour-hex'>" + $("." + className).css("background-color") + "</li></ul>")
                    ;
                }
            });
        });
    });
</script>
</section>

Views/DeveloperGuide/_InlineStyles.cshtml
<section id="dev-guide-inlinestyles">

<h2>Inline Styles</h2>

<h1>Heading 1</h1>
<h2>Heading 2</h2>
<h3>Heading 3</h3>
<h4>Heading 4</h4>
<h5>Heading 5</h5>
<h6>Heading 6</h6>


<h2>Paragraphs</h2>

<p>
Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat
</p>
<p>
El illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum.    
</p>

<h2>Block Quotes</h2>

<blockquote>
    If you can fill the unforgiving minute
    With sixty seconds' worth of distance run,
    Yours is the Earth and everything that's in it,
    And - which is more - you'll be a Man, my son!
</blockquote>

</section>

Views/DeveloperGuide/_InputWidgets.cshtml
<section id="dev-guide-inputwidgets">
<h2>Input Widgets</h2>




    <style>
        #jQueryUiSplitButton .ui-menu { position: absolute; width: 100px; }
    </style>
    

</div>

Views/DeveloperGuide/_LabelsAndBadges.cshtml
@{
    ViewBag.Title = "_LabelsAndBadges";
}

<h2>_LabelsAndBadges</h2>

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}


<div class="build-yourapp-placeholder">
    <h2>Your MVC Boilerplate App</h2>
    <p>Build your app here</p>
    <p>or</p>
    <p>visit the @Html.ActionLink("developer guide", "Index", "DeveloperGuide") for conventions and inspiration</p>
</div>

Views/Shared/_Layout_jQueryOnly.cshtml
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>@ViewBag.Title</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width">

        <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->

        <link rel="stylesheet/less" type="text/css" href="@Url.Content("~/Content/css/mvc.boilerplate/mvc.boilerplate.less")">

        <script src="@Url.Content("~/Content/scripts/lib/modernizr-2.6.1.min.js")"></script>

        <script src="@Url.Content("~/Content/scripts/lib/less-1.3.0.min.js")"></script>
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.0/jquery.min.js"></script>
        <script> window.jQuery || document.write('<script src="@Url.Content("~/Content/scripts/lib/jquery-1.8.0.min.js")"><\/script>')</script>
        <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.9.1/jquery-ui.min.js"></script>
        <script> (jQuery.ui) || document.write('<script src="@Url.Content("~/Content/scripts/lib/jquery-ui-1.9.1.min.js")"><\/script>')</script>

    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="chromeframe">You are using an outdated browser. <a href="http://browsehappy.com/">Upgrade your browser today</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to better experience this site.</p>
        <![endif]-->

        <!-- Add your site or application content here -->
        <div class="content">
        @RenderBody()
        </div>
    </body>
</html>

Views/Test/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout_jQueryOnly.cshtml";    
    ViewBag.Title = "Index";
}

<h2>Index</h2>

    <div id="jQueryUiButtonSet">
        <input type="checkbox" id="check1" /><label for="check1">B</label>
        <input type="checkbox" id="check2" /><label for="check2">I</label>
        <input type="checkbox" id="check3" /><label for="check3">U</label>
    </div>

<script>
    $(document).ready(function () {
        $("#jQueryUiButtonSet").buttonset();
    });
</script>